server:
  port: 4010

spring:
  application:
    name: USER-SERVICE

  datasource:
    url: jdbc:mysql://mysql:3306/hotel_user_database
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: redis
      port: 6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

eureka.instance.prefer-ip-address: true
